version: "3.8"
name: docker-laravel-nginx-mysql-phpmyadmin

services:
    app:
        image: php:8.2-fpm
        container_name: 30Glow
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    webserver:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend_30glow
            MYSQL_USER: root
            MYSQL_PASSWORD: ""
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
